import React,{useEffect,useState} from 'react'
import {Loader, FormField, RenderCard} from '../Components'
import { toast } from 'react-toastify';


const Home = () => {
    const [loading, setLoading] = useState(false);
    const [allPosts, setAllPosts] = useState([]);
    const [searchText, setSearchText] = useState('')
    const [searchedResults, setSearchedResults] = useState([])
    const [searchTimeout, setSearchTimeout] = useState(null)


    const fetchPosts =async ()=>{
        try{
            setLoading(true)
            const url = 'https://concerned-skirt-yak.cyclic.app/api/v1/post'
            const response = await fetch(url,{method:"GET",
                                              headers:{'Content-Type':'application/json'},
                                            })
            if(response.ok){
            const result =await response.json()
            console.log(result.data)
            setAllPosts(result.data.reverse())
            }
        }catch(error){
            toast.info(error)
        }finally{
            setLoading(false)
        }
    }


    const handleSearchChnage =(e)=>{
        clearTimeout(searchTimeout)
        setSearchText(e.target.value)

        setSearchTimeout(
        setTimeout(()=>{
            const searchResult  = allPosts.filter((item)=>item.name.toLowerCase().includes(searchText.toLowerCase()) || 
                item.prompt.toLowerCase().includes(searchText.toLowerCase()))
                setSearchedResults(searchResult)
        },500)
        )
    }


    useEffect(()=>{
        fetchPosts()
    },[])



  return (
   <section className='max-w-7xl mx-auto'>
    <div>
    <h1 className='font-extrabold text[#222328] text-[32px]'>The Cummunity Showcase</h1>
    <p className='mt-2 text-[#666e75] text-[16px] max-w[500px]'>Browse Through a collection of imaginative and Stunning images generated by DALL-E AI</p>
    </div>
    <div className='mt-16'>
        <FormField labelName="Search Post" type="text" name="name" placeholder="Search posts" value={searchText} handleChange={handleSearchChnage}/>
    </div>
    <div className='mt-10'>
        {loading? (
            <div className='flex justify-center items-center'>
                <Loader/>
            </div>
        ):
        (
            <div>
                {searchText && (
                    <h2 className='font-medium text-[#666e75] text-xl mb-3'>Showing results for <span className='text-[#222328]'>{searchText}</span></h2>
                )}
                <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
                {searchText ? (
                    <RenderCard data={searchedResults} title="No search results found" />
                ):
                (
                    <RenderCard data={allPosts} title="No posts found" />
                )
                }

                </div>
            </div>
            
        )
        }
    </div>
    </section>
   
  )
}

export default Home


